### PR TITLE
feat: China support

### PR DESCRIPTION
**Pull request by cdnninja**
Could you test this out @toraidl?

### CODE REVIEW

**Comment by toraidl** [comment]
Sure I can test it @cdnninja

**Comment by toraidl** [comment]
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 96, in check_and_force_update_vehicles
    f"{DOMAIN} - Time differential in seconds: {(started_at_utc - vehicle.last_updated_at).total_seconds()}"  # noqa
TypeError: can't subtract offset-naive and offset-aware datetimes

I tested the API function check_and_force_update_vehicles(600) locally, did not encounter such error. 
image

can you help me out?

**Comment by toraidl** [comment]
Two issue encountered: 
1. Force update failed, falling back to cached: can't subtract offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 96, in check_and_force_update_vehicles
    f"{DOMAIN} - Time differential in seconds: {(started_at_utc - vehicle.last_updated_at).total_seconds()}"  # noqa
TypeError: can't subtract offset-naive and offset-aware datetimes****

2. Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 823, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 568, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 632, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 523, in state
    raise ValueError(
ValueError: Invalid datetime: sensor.di_shi_dai_suo_na_ta_20201103_last_updated_at provides state '2023-05-04 09:49:12.243989', which is missing timezone information

The first issue I encountered was related to the function check_and_force_update_vehicles(). Although the function was able to run without any issues locally, it couldn't function properly due to the local timezone being set to UTC+8.  the function uses the UTC timezone to minimize UTC+8 datetime, which causes inaccuracies in the results.

**Comment by toraidl** [comment]
@cdnninja I'm wondering if it's possible to test the hyundai_kia_connect_api locally with kia_uvo custom_componment? By testing locally, I can quickly troubleshoot issues.

**Comment by cdnninja** [comment]
It's a bit of a pain but can be done.  I'll grab the link on instructions when I can.  

I suspect the issue is related to line 289 of the api file.  All times need a time zone or the comparison will fail to current time.  Make sure the value coming from the api has a tz and is being parsed correctly to ensure python recognizes it.

**Comment by toraidl** [comment]
image
It seems like correct?

**Comment by toraidl** [comment]
I believe I have identified the problem and have submitted a PR to the API repository.
After testing it locally, it appears the issue has been resolved. 
image

**Comment by cdnninja** [comment]
@toraidl Thanks for all the work on this! I will merge this now.

**Pull request merged**
