### PR TITLE
fix: force seats to be integers

### PR DESCRIPTION
**Pull request by cdnninja**
Can someone confirm this tests out? I no longer have a car to test this with.

### CODE REVIEW

**Comment by chasebolt** [comment]
@cdnninja I will try and test this out today. what is the best way to test it?

**Comment by cdnninja** [comment]
Easiest way would be to edit the file in your custom_components directory with the changes here. Restart HA after that and it will take effect.

**Comment by cdnninja** [comment]
I have edited the code.  Let me know if that now looks correct.  

The values supported are car dependant.

**Comment by tonygauderman** [comment]
Yea, that looks correct.  I have copied the lastest file contents out and replaced my entire file and will restart and test.  For the values, I may just need to play with the numbers with a manual call.  I was testing from an automation, could test from developer tools or node red to send different values and see what happens.  Do you know how the integration determines what each vehicles valid values are?

**Comment by cdnninja** [comment]
Today we have no way to know what cars support what.   We pass the value as provided.

**Comment by tonygauderman** [comment]
Values are provided when the integration and vehicles are added?

**Comment by cdnninja** [comment]
No values are static.  We sniffed and understood them best we could.  They could differ from car or region though.  

They are shown here.  The number is passed straight to the api and consumed by Kia Hyundai. 

https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/master/custom_components/kia_uvo/services.yaml

**Comment by tonygauderman** [comment]
I suspect in my case, neither of my vehicles support setting the seat settings.  They don't from the official app, and I was trying to use the integration to get around that thinking it was a limitation on the app, not my vehicles.

**Comment by cdnninja** [comment]
If your native app doesn't have it the integration won't work for it either.

**Pull request merged**
