### PR TITLE
feat: set SOC levels as number instead of slider

### PR DESCRIPTION
**Pull request by bouwew**
This update will improve the usability of the numbers:
image

### CODE REVIEW

**Comment by fuatakgun** [comment]
That is nice, i am just worried if the user uses the up/down buttons, it would call the service for each click, right?

**Comment by bouwew** [comment]
No it doesn't. I use this method in the Plugwise integration, I've tested, it waits a while until the changing is done, then the connected service is called. This is all handled in the frontend.

Wait, what is the default step-size, let me check...

**Comment by bouwew** [comment]
I see you have set it to 10, no change needed, all good :)

**Comment by bouwew** [comment]
My main reason for this change is the visibility of the value: the slider does not provide any info on the set value, mode BOX does.

**Review by cdnninja — APPROVED** [review]

**Comment by bouwew** [comment]
FYI, the SOC-levels were already numbers, the default representation of a number is via a slider. The alternative is representation via a box :)

About your question, you want to avoid sending two times when a user changes both the AC and DC setpoints?
The best place to do this I think is in the `set_charge_limits()` function.
I don't have a ready-made solution for you, but I'll give it some thought.

**Comment by cdnninja** [comment]
> 

Yes, we have a bug where it sends two back to back calls to the car.  The second one is rejected due to duplicate since the API is slow to process items.  I have been thinking about an easy way to bundle them.  Ideally waiting say 30 seconds and grabbing the current UI values for both to send.  I have been thinking on it but no pro just a hobby dev.  Last action tracking is one option but will take more effort still and EU doesn't support it.

**Pull request merged**
