### PR TITLE
fix(EU): stamp generation

### PR DESCRIPTION
**Pull request by kalaws**
Like so?

### CODE REVIEW

**Comment by erikgeurts** [comment]
For future reference, this is a fix for #686 .

**Comment by mvroosmalen1970** [comment]
> For future reference, this is a fix for #686 .

Confirmed solved! Thanks

**Comment by artursulkowski** [comment]
I can also confirm that it's working with new version of hyundai_kia_connect_api.
My setup: Hyundai Bluelink, region EU
How about new official release so it becomes available over HACS?

**Comment by fuatakgun** [comment]
Done

**Comment by erikgeurts** [comment]
I see the latest release got bumped to 2.0.17 just now, but that doesn't include this particular change. Is there a 2.0.18 pending?

**Comment by cdnninja** [comment]
> I see the latest release got bumped to 2.0.17 just now, but that doesn't include this particular change. Is there a 2.0.18 pending?

If you want to see the key change go look at our underlying api and what changed in it.  This bumps to use that new version.

**Comment by erikgeurts** [comment]
What I mean is there is still no formal release 2.0.18 or otherwise at https://github.com/Hyundai-Kia-Connect/kia_uvo/releases that includes this. As such, unsuspecting Home Assistant users that have this integration installed via HACS won't know there's a fix for the problem they must be facing by now.

**Comment by cdnninja** [comment]
> What I mean is there is still no formal release 2.0.18 or otherwise at https://github.com/Hyundai-Kia-Connect/kia_uvo/releases that includes this. As such, unsuspecting Home Assistant users that have this integration installed via HACS won't know there's a fix for the problem they must be facing by now.

2.0.17. Looks like the commit didn't get caught by our GitHub action for release notes.  It is included though.

**Comment by erikgeurts** [comment]
Ah, yes, I see it now, after comparing 2.0.16 with 2.0.17:
https://github.com/Hyundai-Kia-Connect/kia_uvo/compare/v2.10.6...v2.10.7

**Pull request merged**
