### PR TITLE
feat: German Config Translation

### PR DESCRIPTION
**Pull request by 4homeassistant**
German translation

### CODE REVIEW

**Comment by 4homeassistant** [comment]
@cdnninja, what did I make wrong? First fail seems to be the title that you already fixed, second is 'codespell' without any hint what might be spelled wrong. I just copied and pasted the original file and replaced the english text. Will have another look tomorrow and compare both files line by line.
Sorry my friend, I really like to help but have zero experience with Github. :-/

**Comment by cdnninja** [comment]
You may be fine! Codespell may not work for other languages.  I'll double check when home.  Initial impressions are it may be fine.  If so I'll merge it.

**Comment by 4homeassistant** [comment]
> You may be fine! Codespell may not work for other languages. I'll double check when home. Initial impressions are it may be fine. If so I'll merge it.

I had a look into the log and it seems that a couple of German words are marked as wrong. Does Github perform dictionary checks? 😳

**Comment by 4homeassistant** [comment]
By the way, is there any source that explains the different estimated-time-to-100%-SOC entities?
I doubt that these do really make sense for universal use. 
Example Kona EV (small battery) in German power grid:
Portable charger (Schuko / CEE): 2.3 / 3.6 kW
Home charging station (11/22 kW max.): 3.6 kW
AC public fast charger (22 kW): 3.6 kW
DC public fast charger (50-350 kW max.): up to 
The reported values in my HA do not really match the options above.
B4AAB1CA-B95C-46BE-9247-F5C868FAA63D

**Comment by cdnninja** [comment]
> > You may be fine! Codespell may not work for other languages. I'll double check when home. Initial impressions are it may be fine. If so I'll merge it.
> 
> 
> 
> I had a look into the log and it seems that a couple of German words are marked as wrong. Does Github perform dictionary checks? 😳

Yes but by my choice.  Lots of actions exist to check items.  This is one I setup.

**Comment by 4homeassistant** [comment]
> > > You may be fine! Codespell may not work for other languages. I'll double check when home. Initial impressions are it may be fine. If so I'll merge it.
> > 
> > 
> > I had a look into the log and it seems that a couple of German words are marked as wrong. Does Github perform dictionary checks? 😳
> 
> Yes but by my choice. Lots of actions exist to check items. This is one I setup.

Good to know 😉

**Pull request merged**
