### PR TITLE
feat: Dutch Language Support

### PR DESCRIPTION
**Pull request by erikgeurts**
First iteration

### CODE REVIEW

**Comment by erikgeurts** [comment]
Since this is my first attempt at contributing to this repository, I'd appreciate any tips you might have to fix the failing checks.

**Comment by cdnninja** [comment]
> My guess is that the problem stems from this: image

Could be!  I removed codespell since it isn't helpful for non english.  That leaves us with this as the key:

image

Any character you can swap that for to keep utf8?

**Comment by cdnninja** [comment]
Quick note I have also just moved most of the services details to the translation file so this will need to be done for the dutch file too.

**Comment by cdnninja** [comment]
Managed to convert to UTF 8 without loosing the character.  This seems to have resolved.  Thanks for the contribution!

**Comment by cdnninja** [comment]
Do you know how we can do that using the home assistant spec?  I know it can be done for select options but not sure on others.  I am up for it if possible!

**Comment by fuatakgun** [comment]
Can we refer to other strings?

https://developers.home-assistant.io/docs/internationalization/core

**Pull request merged**
